# Generated by Django 2.0.7 on 2018-08-15 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='在程式中當作 Key 來對應。(Unique)', max_length=32, unique=True, verbose_name='區域名稱')),
                ('show_text', models.CharField(help_text='用於 排放潛勢 及 IoT 數據回朔', max_length=128, verbose_name='顯示名稱')),
                ('min_lat', models.FloatField(verbose_name='經緯度邊界 - 最低緯度')),
                ('max_lat', models.FloatField(verbose_name='經緯度邊界 - 最高緯度')),
                ('min_lon', models.FloatField(verbose_name='經緯度邊界 - 最小經度')),
                ('max_lon', models.FloatField(verbose_name='經緯度邊界 - 最大經度')),
                ('center_lat', models.FloatField(help_text='用於排放潛勢', verbose_name='中間點 - 緯度')),
                ('center_lon', models.FloatField(help_text='用於排放潛勢', verbose_name='中間點 - 經度')),
                ('zoom_level', models.PositiveSmallIntegerField(default=14, help_text='用於排放潛勢')),
                ('square_radius', models.PositiveSmallIntegerField(default=80, help_text='用於排放潛勢')),
                ('circle_active', models.BooleanField(default=False, verbose_name='是否顯示在排放潛勢選單')),
            ],
        ),
    ]
