# Generated by Django 2.0.7 on 2018-08-16 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_configs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='(Unique)', max_length=254, unique=True, verbose_name='收件者 Email')),
                ('risks', models.CharField(max_length=32)),
                ('area', models.TextField(blank=True)),
            ],
        ),
    ]
