# Generated by Django 2.0.7 on 2018-10-01 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature_configs', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='event_active',
            field=models.BooleanField(default=True, verbose_name='是否顯示在 事件清單 及 IoT數據回朔'),
        ),
        migrations.AlterField(
            model_name='area',
            name='center_lat',
            field=models.FloatField(blank=True, help_text='用於排放潛勢', verbose_name='中間點 - 緯度'),
        ),
        migrations.AlterField(
            model_name='area',
            name='center_lon',
            field=models.FloatField(blank=True, help_text='用於排放潛勢', verbose_name='中間點 - 經度'),
        ),
        migrations.AlterField(
            model_name='area',
            name='square_radius',
            field=models.PositiveSmallIntegerField(blank=True, default=80, help_text='用於排放潛勢'),
        ),
        migrations.AlterField(
            model_name='area',
            name='zoom_level',
            field=models.PositiveSmallIntegerField(blank=True, default=14, help_text='用於排放潛勢'),
        ),
    ]
