# Generated by Django 2.0.7 on 2018-10-02 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feature_configs', '0004_auto_20181001_0812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='area',
            name='center_lat',
        ),
        migrations.RemoveField(
            model_name='area',
            name='center_lon',
        ),
        migrations.RemoveField(
            model_name='area',
            name='zoom_level',
        ),
    ]
