FROM cameo/epa-python-base:latest

RUN apk add --update --no-cache --virtual .runtime-deps \
        openblas \
	&& apk add --no-cache --virtual .build-deps \
        g++ \
        musl-dev \
        openblas-dev \
    && pip3 --no-cache-dir install \
        SciPy==1.1.0 \
        scikit-learn==0.19.2 \
    && apk del .build-deps

