---
## Default Kibana configuration from kibana-docker.
## from https://github.com/elastic/kibana-docker/blob/master/build/kibana/config/kibana.yml
#
server.name: kibana
server.host: "0"
elasticsearch.url: http://elasticsearch:9200

server.basePath: "/_/elk"
server.rewriteBasePath: true
xpack.reporting.csv.maxSizeBytes: 1000000000
