---

code: "566"
project: "國家空氣品質測站監測資料（檢核後小時值）"
api_key: "PKBGY29WAM9XAXF7C0"


# MQTT

MQTTReceiver:
  args: {}
  input: mqtt_data
  output: kafka_mqtt_data


MQTTETLer:
  args: &etl_pipelines
    etl:
      - take_first:
          field: value
      - to_numeric:
          fields:
            - value
      - replace_value:
          field: value
          old_values:
            - NA
            - ""
          new_value: null
      - rename:
          fields:
            deviceId: device_id
      - rename_from_field_value:
          field: value
          from_field: id
      - append_device_name_lat_lon:
          device_cls_name: EpaStationTextarDevice
      - select:
          fields:
            - time
            - device_id
            - name
            - lat
            - lon
            - amb_temp
            - ch4
            - co
            - co2
            - flow
            - nmhc
            - no
            - no2
            - nox
            - "o3"
            - pm10
            - pm10_test
            - pm2_5
            - pm2_5_ori
            - pm2_5_test
            - pressure
            - ph_cond
            - ph_rain
            - rain_int
            - rainfall
            - rh
            - shelt_temp
            - so2
            - thc
            - uva
            - uvb
            - wd_hr
            - wind_direct
            - wind_speed
            - ws_hr
  input: kafka_mqtt_data
  output: kafka_etl_data


# RESTful

RawdataUpdater:
  args:
    time_span_days: 400
    device_class: EpaStationTextarDevice
    data_class: EpaStationTextarRawData
    data_count_class: EpaStationTextarRawDataCount
  input: http_rawdata
  output: kafka_rest_data


RESTETLer:
  args:
    << : *etl_pipelines
  input: kafka_rest_data
  output: kafka_etl_data


DeviceInformer:
  args:
    etl:
      - update_from_dict_list:
          field: attributes
          drop: true
      - rename:
          fields:
            id: device_id
            deviceType: device_type
            ownerId: owner_id
            manufacturerId: manufacturer_id
            subDeviceType: sub_device_type
      - to_bool:
          fields:
            - mobile
      - select:
          fields:
            - device_id
            - name
            - desc
            - type
            - lat
            - lon
            - alt
            - reference
            - display
            - device_type
            - owner_id
            - mobile
            - outdoor
            - manufacturer_id
            - sub_device_type
            - sensors
  input: http_device
  output: db_device


CountUpdater:
  input: http_count
  output: db_count


# Save to DB

DBShelver:
  args:
    postpone_write: True
  input: kafka_etl_data
  output: db_data


ESShelver:
  args:
    postpone_write: True
    postpone_gather_keys:
      - time
      - device_id
    etl:
      - datetime_to_isoformat:
          field: time
          parsing_format: "%Y-%m-%d %H:%M:%S.%f"
          zoneinfo: Asia/Taipei
  input: kafka_etl_data
  output: es_data


DataObject:
  input: kafka_etl_data
  output: kafka_data_object



handlers:
  # SOURCEs
  mqtt_data:
    handler: MQTTHandler
    args:
      topics:
        - /v1/project/566/device/+/sensor/+/rawdata
  http_rawdata:
    handler: HTTPHandler
  http_count:
    handler: HTTPHandler
  http_device:
    handler: DeviceHTTPHandler

  # KAFKA QUEUEs
  kafka_mqtt_data:
    handler: KafkaHandler
    args:
      topics:
        - rawdata.epa_station.566.textar.mqtt
  kafka_rest_data:
    handler: KafkaHandler
    args:
      topics:
        - rawdata.epa_station.566.textar.rest
      config: {}
  kafka_etl_data:
    handler: KafkaHandler
    args:
      topics:
        - rawdata.epa_station.566.textar.etl
  kafka_data_object:
    handler: DataObjectKafkaHandler
    args:
      model: EpaStationTextarRawData

  # STORAGEs
  es_data:
    handler: ESHandler
    args:
      index: rawdata.epa_station.566.textar
      id_fields:
        - time
        - device_id
  db_data:
    handler: SqlAlchemyHandler
    args:
      model: EpaStationTextarRawData
  db_count:
    handler: SqlAlchemyHandler
    args:
      model: EpaStationTextarRawDataCount
  db_device:
    handler: SqlAlchemyHandler
    args:
      model: EpaStationTextarDevice

